[tool.poetry]
name = "poketwo-support"
version = "0.1.0"
description = ""
authors = ["Oliver Ni <oliver.ni@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
"discord.py" = {git = "https://github.com/Rapptz/discord.py.git", rev = "master"}
motor = "^2.3.0"
jishaku = "^1.19.2"
discord-ext-menus = {git = "https://github.com/Rapptz/discord-ext-menus.git"}
dnspython = "^2.0.0"
discord-ext-events = { git = "https://github.com/Ext-Creators/discord-ext-events.git" }
durations-nlp = "^1.0.1"
aioredis = "^1.3.1"
discord-ext-menus-views = {git = "https://github.com/oliver-ni/discord-ext-menus-views.git"}

[tool.poetry.dev-dependencies]
black = "^20.8b1"

[tool.black]
line-length = 100

[build-system]
requires = ["poetry-core>=1.0.0a5"]
build-backend = "poetry.core.masonry.api"
